### ISSUE TITLE
how to bypass cloudflare browser check?

### ISSUE THREAD

**Issue by KFERMercer** [bcmk/siren#12]
in [lib/chaturbate.go](https://github.com/bcmk/siren/blob/master/lib/chaturbate.go), it's not see the relevant solution for cloudflares check, but evethings works just fine in [t.me/ChaturbateAlarmBot](https://t.me/ChaturbateAlarmBot), how did you achieve this?

**Comment by bcmk** [comment]
I use Chaturbate API
