### ISSUE TITLE
@ChaturbateAlarmBot doesn't notify me at all

### ISSUE THREAD

**Issue by johnwig** [bcmk/siren#14]
I have been using @ChaturbateAlarmBot since 12th July to monitor 1 model. But it never notify me.

![Screenshot_20230807-153726_Telegram Beta](https://github.com/bcmk/siren/assets/50834078/6614d28f-89f9-4c46-92a7-d4acb9a92b86)

**Comment by bcmk** [comment]
Unfortunately, there are certain settings the model can adjust that prevent them from being advertised in the API, and this is one of those cases
